version: '3'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: unless-stopped
    volumes:
      - TBC
    ports:
      - TBC
    networks:
      - infrastructure

volumes:
  TBC
  
networks:
  infrastructure:
    ipam:
      config:
        - subnet: 172.31.0.0/16
